apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: crew-ai-test25102111
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/crew-ai-test25102111:27eb2595a8442444d7fa50aaf17730bf196f43b3@sha256:f1b4f69c0f74117a28c4b497d9ec605a617ece60560112e8df827815195b8844 # use pre-built to bootstrap
          name: app-inference
